DROP DATABASE UCC;
CREATE DATABASE UCC;
USE UCC;

CREATE TABLE PROFESOR(
    CC_PROFESOR VARCHAR(3) PRIMARY KEY,
    NOMBRE_PROFESOR VARCHAR(80) NOT NULL,
    CORREO VARCHAR(80) NOT NULL
);

CREATE TABLE ING_SISTEMAS( #CURSO xd
    COD_CURSO INT PRIMARY KEY,
    NOMBRE_CURSO VARCHAR(80) NOT NULL,
    CC_PROFESOR VARCHAR(3),
    HORA_INICIO TIME NOT NULL,
    HORA_FIN TIME NOT NULL,

    FOREIGN KEY (CC_PROFESOR) REFERENCES PROFESOR(CC_PROFESOR)
);

CREATE TABLE ESTUDIANTE(
    CC_ESTUDIANTE VARCHAR(3) PRIMARY KEY,
    COD_CURSO INT,
    NOMBRE_ESTUDIANTE VARCHAR(80) NOT NULL,
    NOTA FLOAT,

    FOREIGN KEY (COD_CURSO) REFERENCES ING_SISTEMAS(COD_CURSO)
);
