SELECT e.CC_ESTUDIANTE,NOMBRE, c.COD_CURSO, NOTA FROM CURSO c, INSCRIPCION_CURSO i, ESTUDIANTE e WHERE i.CC_ESTUDIANTE = e.CC_ESTUDIANTE AND i.COD_CURSO=c.COD_CURSO;


SELECT * FROM CURSO;

UPDATE CURSO SET ID_PROFESOR = 2 WHERE COD_CURSO = 90 OR COD_CURSO =70